using Newtonsoft.Json;
using WABA360Dialog.Common.Converters;

namespace WABA360Dialog.Common.Enums
{
    [JsonConverter(typeof(WhatsAppLanguageConverter))]
    public enum WhatsAppLanguage
    {
        Afrikaans = 1,
        Albanian = 2,
        Arabic = 3,
        Azerbaijani = 4,
        Bengali = 5,
        Bulgarian = 6,
        Catalan = 7,
        Chinese_CN = 8,
        Chinese_HK = 9,
        Chinese_TW = 10,
        Croatian = 11,
        Czech = 12,
        Danish = 13,
        Dutch = 14,
        English = 15,
        English_UK = 16,
        English_US = 17,
        Estonian = 18,
        Filipino = 19,
        Finnish = 20,
        French = 21,
        Georgian = 22,
        German = 23,
        Greek = 24,
        Gujarati = 25,
        Hausa = 26,
        Hebrew = 27,
        Hindi = 28,
        Hungarian = 29,
        Indonesian = 30,
        Irish = 31,
        Italian = 32,
        Japanese = 33,
        Kannada = 34,
        Kazakh = 35,
        Kinyarwanda = 36,
        Korean = 37,
        Kyrgyz = 38,
        Lao = 39,
        Latvian = 40,
        Lithuanian = 41,
        Macedonian = 42,
        Malay = 43,
        Malayalam = 44,
        Marathi = 45,
        Norwegian = 46,
        Persian = 47,
        Polish = 48,
        Portuguese_BR = 49,
        Portuguese_POR = 50,
        Punjabi = 51,
        Romanian = 52,
        Russian = 53,
        Serbian = 54,
        Slovak = 55,
        Slovenian = 56,
        Spanish = 57,
        Spanish_ARG = 58,
        Spanish_SPA = 59,
        Spanish_MEX = 60,
        Swahili = 61,
        Swedish = 62,
        Tamil = 63,
        Telugu = 64,
        Thai = 65,
        Turkish = 66,
        Ukrainian = 67,
        Urdu = 68,
        Uzbek = 69,
        Vietnamese = 70,
        Zulu = 71,
    }
}